// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Circle_Monitor_Switch_V2.1b

#ifndef _CIRCLE_MONITOR_SWITCH_V2_1B_UI_COMP_HOOK_H
#define _CIRCLE_MONITOR_SWITCH_V2_1B_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_dim_arc_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
