// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Circle_Monitor_Switch_V2.1b

#include "../ui.h"


// COMPONENT dim_arc

lv_obj_t * ui_dim_arc_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_dim_arc;
    cui_dim_arc = lv_arc_create(comp_parent);
    lv_obj_set_width(cui_dim_arc, 180);
    lv_obj_set_height(cui_dim_arc, 180);
    lv_obj_set_align(cui_dim_arc, LV_ALIGN_CENTER);
    lv_arc_set_value(cui_dim_arc, 50);
    lv_obj_set_style_bg_img_recolor(cui_dim_arc, lv_color_hex(0xF8712B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor_opa(cui_dim_arc, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_set_style_arc_color(cui_dim_arc, lv_color_hex(0x37F4FA), LV_PART_INDICATOR | LV_STATE_PRESSED);
    lv_obj_set_style_arc_opa(cui_dim_arc, 255, LV_PART_INDICATOR | LV_STATE_PRESSED);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DIM_ARC_NUM);
    children[UI_COMP_DIM_ARC_DIM_ARC] = cui_dim_arc;
    lv_obj_add_event_cb(cui_dim_arc, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_dim_arc, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_dim_arc_create_hook(cui_dim_arc);
    return cui_dim_arc;
}

