// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Circle_Monitor_Switch_V2.1b

#ifndef _UI_COMP_DIM_ARC_H
#define _UI_COMP_DIM_ARC_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT dim_arc
#define UI_COMP_DIM_ARC_DIM_ARC 0
#define _UI_COMP_DIM_ARC_NUM 1
lv_obj_t * ui_dim_arc_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
