// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Circle_Monitor_Switch_V2.1b

#include "../ui.h"

void ui_Clock_Screen_screen_init(void)
{
    ui_Clock_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Clock_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Clock_Screen, lv_color_hex(0x0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clock = lv_label_create(ui_Clock_Screen);
    lv_obj_set_width(ui_clock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clock, "12:03");
    lv_obj_set_style_text_color(ui_clock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clock, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather = lv_img_create(ui_Clock_Screen);
    lv_img_set_src(ui_weather, &ui_img_cloud2rain3day_png);
    lv_obj_set_width(ui_weather, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_weather, LV_SIZE_CONTENT);    /// 107
    lv_obj_set_x(ui_weather, 3);
    lv_obj_set_y(ui_weather, 68);
    lv_obj_set_align(ui_weather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weather, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
