// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Circle_Monitor_Switch_V2.1b

#include "../ui.h"

void ui_CCT_Screen_screen_init(void)
{
    ui_CCT_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CCT_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CCT_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CCT_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cct_arc = lv_arc_create(ui_CCT_Screen);
    lv_obj_set_width(ui_cct_arc, 220);
    lv_obj_set_height(ui_cct_arc, 220);
    lv_obj_set_align(ui_cct_arc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_cct_arc, 50);
    lv_obj_set_style_bg_img_recolor(ui_cct_arc, lv_color_hex(0xefd56d), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_cct_arc, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_set_style_arc_opa(ui_cct_arc, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_cct_arc, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_set_style_arc_color(ui_cct_arc, lv_color_hex(0xefd56d), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_cct_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_cct_arc, lv_color_hex(0xefd56d), LV_PART_INDICATOR | LV_STATE_PRESSED);
    lv_obj_set_style_arc_opa(ui_cct_arc, 255, LV_PART_INDICATOR | LV_STATE_PRESSED);

    lv_obj_set_style_bg_opa(ui_cct_arc, LV_OPA_TRANSP, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cct_arc, LV_OPA_TRANSP, LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_pad_all(ui_cct_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_cct_arc, 0, LV_PART_KNOB | LV_STATE_PRESSED);

    ui_cct_label = lv_label_create(ui_CCT_Screen);
    lv_obj_set_width(ui_cct_label, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(ui_cct_label, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_align(ui_cct_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cct_label, "3650K");
    lv_obj_set_style_text_color(ui_cct_label, lv_color_hex(0xefd56d), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cct_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cct_label, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cct_label, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempcolor_label = lv_label_create(ui_CCT_Screen);
    lv_obj_set_width(ui_tempcolor_label, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_tempcolor_label, LV_SIZE_CONTENT);
    // lv_obj_align_to(ui_tempcolor_label, ui_dim_label, LV_ALIGN_OUT_BOTTOM_MID, -12, 0); // cách label % 4px
    lv_obj_align(ui_tempcolor_label, LV_ALIGN_CENTER, 0, 30);
    lv_label_set_text(ui_tempcolor_label, "COLORTEMP");
    lv_obj_set_style_text_color(ui_tempcolor_label, lv_color_hex(0xefd56d), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempcolor_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tempcolor_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_tempcolor_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT); // giãn chữ cho giống nhãn/label thường thấy
    lv_obj_set_style_text_font(ui_tempcolor_label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);


}
