// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Circle_Monitor_Switch_V2.1b

#include "../ui.h"

void ui_Dim_Screen_screen_init(void)
{
   /*
   ui_Dim_Screen = lv_obj_create(NULL);
   lv_obj_clear_flag(ui_Dim_Screen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
   lv_obj_set_style_bg_color(ui_Dim_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_bg_opa(ui_Dim_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

   ui_dim_arc = lv_arc_create(ui_Dim_Screen);
   lv_obj_set_width(ui_dim_arc, 180);
   lv_obj_set_height(ui_dim_arc, 180);
   lv_obj_set_align(ui_dim_arc, LV_ALIGN_CENTER);
   lv_arc_set_value(ui_dim_arc, 50);
   lv_obj_set_style_bg_img_recolor(ui_dim_arc, lv_color_hex(0xF8712B), LV_PART_MAIN | LV_STATE_PRESSED);
   lv_obj_set_style_bg_img_recolor_opa(ui_dim_arc, 255, LV_PART_MAIN | LV_STATE_PRESSED);

   lv_obj_set_style_arc_color(ui_dim_arc, lv_color_hex(0xC0C0C0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
   lv_obj_set_style_arc_opa(ui_dim_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
   lv_obj_set_style_arc_color(ui_dim_arc, lv_color_hex(0xC0C0C0), LV_PART_INDICATOR | LV_STATE_PRESSED);
   lv_obj_set_style_arc_opa(ui_dim_arc, 255, LV_PART_INDICATOR | LV_STATE_PRESSED);

   lv_obj_set_style_bg_color(ui_dim_arc, lv_color_hex(0xC0C0C0), LV_PART_KNOB | LV_STATE_DEFAULT);
   lv_obj_set_style_bg_opa(ui_dim_arc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
   lv_obj_set_style_bg_grad_color(ui_dim_arc, lv_color_hex(0xBE2929), LV_PART_KNOB | LV_STATE_DEFAULT);

   ui_dim_label = lv_label_create(ui_Dim_Screen);
   lv_obj_set_width(ui_dim_label, LV_SIZE_CONTENT);  /// 3
   lv_obj_set_height(ui_dim_label, LV_SIZE_CONTENT); /// 3
   lv_obj_set_align(ui_dim_label, LV_ALIGN_CENTER);
   lv_label_set_text(ui_dim_label, "50%");
   lv_obj_set_style_text_color(ui_dim_label, lv_color_hex(0xF2EDED), LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_text_opa(ui_dim_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_text_align(ui_dim_label, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_text_font(ui_dim_label, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);
   */

   ui_Dim_Screen = lv_obj_create(NULL);
   lv_obj_clear_flag(ui_Dim_Screen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
   lv_obj_set_style_bg_color(ui_Dim_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_bg_opa(ui_Dim_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

   ui_dim_arc = lv_arc_create(ui_Dim_Screen);
   lv_obj_set_width(ui_dim_arc, 220);
   lv_obj_set_height(ui_dim_arc, 220);
   lv_obj_set_align(ui_dim_arc, LV_ALIGN_CENTER);
   lv_arc_set_value(ui_dim_arc, 50);
   lv_obj_set_style_bg_img_recolor(ui_dim_arc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
   lv_obj_set_style_bg_img_recolor_opa(ui_dim_arc, 255, LV_PART_MAIN | LV_STATE_PRESSED);

   /* Ẩn hẳn track nền (PART_MAIN) -> cung sẽ KHÔNG còn hiện đủ độ dài nữa,
      chỉ còn phần indicator (đúng theo giá trị) là hiển thị */
   lv_obj_set_style_arc_opa(ui_dim_arc, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_arc_opa(ui_dim_arc, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_PRESSED);

   lv_obj_set_style_arc_color(ui_dim_arc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
   lv_obj_set_style_arc_opa(ui_dim_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
   lv_obj_set_style_arc_color(ui_dim_arc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_PRESSED);
   lv_obj_set_style_arc_opa(ui_dim_arc, 255, LV_PART_INDICATOR | LV_STATE_PRESSED);

   /* Bỏ hình tròn (knob) trượt trên slider: cho trong suốt + padding = 0
      Lưu ý: arc vẫn kéo/chỉnh giá trị được bình thường (chạm vào vòng cung),
      chỉ là không còn hình tròn hiển thị ở đầu mút nữa. */
   lv_obj_set_style_bg_opa(ui_dim_arc, LV_OPA_TRANSP, LV_PART_KNOB | LV_STATE_DEFAULT);
   lv_obj_set_style_bg_opa(ui_dim_arc, LV_OPA_TRANSP, LV_PART_KNOB | LV_STATE_PRESSED);
   lv_obj_set_style_pad_all(ui_dim_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
   lv_obj_set_style_pad_all(ui_dim_arc, 0, LV_PART_KNOB | LV_STATE_PRESSED);

   ui_dim_label = lv_label_create(ui_Dim_Screen);
   lv_obj_set_width(ui_dim_label, LV_SIZE_CONTENT);  /// 3
   lv_obj_set_height(ui_dim_label, LV_SIZE_CONTENT); /// 3
   lv_obj_set_align(ui_dim_label, LV_ALIGN_CENTER);
   lv_label_set_text(ui_dim_label, "50%");
   lv_obj_set_style_text_color(ui_dim_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_text_opa(ui_dim_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_text_align(ui_dim_label, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_text_font(ui_dim_label, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

   ui_brightness_label = lv_label_create(ui_Dim_Screen);
   lv_obj_set_width(ui_brightness_label, LV_SIZE_CONTENT);
   lv_obj_set_height(ui_brightness_label, LV_SIZE_CONTENT);
   //  lv_obj_align_to(ui_brightness_label, ui_dim_label, LV_ALIGN_OUT_BOTTOM_MID, 0, 0); // cách label % 4px
   lv_obj_align(ui_brightness_label, LV_ALIGN_CENTER, 0, 30);
   lv_label_set_text(ui_brightness_label, "BRIGHTNESS");
   lv_obj_set_style_text_color(ui_brightness_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_text_opa(ui_brightness_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_text_align(ui_brightness_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_text_letter_space(ui_brightness_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT); // giãn chữ cho giống nhãn/label thường thấy
   lv_obj_set_style_text_font(ui_brightness_label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
}
