// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Circle_Monitor_Switch_V2.1b

#include "../ui.h"

void ui_RGB_Screen_screen_init(void)
{
    ui_RGB_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RGB_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RGB_Screen, lv_color_hex(0x0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RGB_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rgb_wheel = lv_colorwheel_create(ui_RGB_Screen, true);
    lv_obj_set_width(ui_rgb_wheel, 220);
    lv_obj_set_height(ui_rgb_wheel, 220);
    lv_obj_set_align(ui_rgb_wheel, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_main_stop(ui_rgb_wheel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_rgb_wheel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_rgb_wheel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_rgb_wheel, 8, LV_PART_KNOB);

    ui_RGB_circle = lv_obj_create(ui_RGB_Screen);
    lv_obj_set_width(ui_RGB_circle, 65);
    lv_obj_set_height(ui_RGB_circle, 65);
    lv_obj_set_align(ui_RGB_circle, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RGB_circle, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_RGB_circle, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_RGB_circle, LV_DIR_TOP);
    lv_obj_set_style_radius(ui_RGB_circle, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RGB_circle, lv_color_hex(0xFC0707), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RGB_circle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
}
