// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Circle_Monitor_Switch_V2.1b

#include "../ui.h"

void ui_Ralli_Screen_screen_init(void)
{
    ui_Ralli_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Ralli_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Ralli_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ralli_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Logo = lv_img_create(ui_Ralli_Screen);
    lv_img_set_src(ui_Logo, &ui_img_logoralli_png);
    lv_obj_set_width(ui_Logo, LV_SIZE_CONTENT);   /// 180
    lv_obj_set_height(ui_Logo, LV_SIZE_CONTENT);    /// 111
    lv_obj_set_align(ui_Logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
