// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Circle_Monitor_Switch_V2.1b

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Ralli_Screen
void ui_Ralli_Screen_screen_init(void);
lv_obj_t * ui_Ralli_Screen;
lv_obj_t * ui_Logo;


// SCREEN: ui_Dim_Screen
void ui_Dim_Screen_screen_init(void);
lv_obj_t * ui_Dim_Screen;
lv_obj_t * ui_dim_arc;
lv_obj_t * ui_dim_label;
lv_obj_t * ui_brightness_label;


// SCREEN: ui_CCT_Screen
void ui_CCT_Screen_screen_init(void);
lv_obj_t * ui_CCT_Screen;
lv_obj_t * ui_cct_arc;
lv_obj_t * ui_cct_label;
lv_obj_t * ui_tempcolor_label;


// SCREEN: ui_RGB_Screen
void ui_RGB_Screen_screen_init(void);
lv_obj_t * ui_RGB_Screen;
lv_obj_t * ui_rgb_wheel;
lv_obj_t * ui_RGB_circle;


// SCREEN: ui_Clock_Screen
void ui_Clock_Screen_screen_init(void);
lv_obj_t * ui_Clock_Screen;
lv_obj_t * ui_clock;
lv_obj_t * ui_weather;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Ralli_Screen_screen_init();
    ui_Dim_Screen_screen_init();
    ui_CCT_Screen_screen_init();
    ui_RGB_Screen_screen_init();
    ui_Clock_Screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    // lv_disp_load_scr(ui_Ralli_Screen); //ui_Ralli_Screen ui_Clock_Screen
}
