// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Circle_Monitor_Switch_V2.1b

#ifndef _CIRCLE_MONITOR_SWITCH_V2_1B_UI_H
#define _CIRCLE_MONITOR_SWITCH_V2_1B_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Ralli_Screen
void ui_Ralli_Screen_screen_init(void);
extern lv_obj_t * ui_Ralli_Screen;
extern lv_obj_t * ui_Logo;
// SCREEN: ui_Dim_Screen
void ui_Dim_Screen_screen_init(void);
extern lv_obj_t * ui_Dim_Screen;
extern lv_obj_t * ui_dim_arc;
extern lv_obj_t * ui_dim_label;
extern lv_obj_t * ui_brightness_label;
// SCREEN: ui_CCT_Screen
void ui_CCT_Screen_screen_init(void);
extern lv_obj_t * ui_CCT_Screen;
extern lv_obj_t * ui_cct_arc;
extern lv_obj_t * ui_cct_label;
extern lv_obj_t * ui_tempcolor_label;
// SCREEN: ui_RGB_Screen
void ui_RGB_Screen_screen_init(void);
extern lv_obj_t * ui_RGB_Screen;
extern lv_obj_t * ui_rgb_wheel;
extern lv_obj_t * ui_RGB_circle;
// SCREEN: ui_Clock_Screen
void ui_Clock_Screen_screen_init(void);
extern lv_obj_t * ui_Clock_Screen;
extern lv_obj_t * ui_clock;
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_logoralli_png);    // assets/LogoRalli.png
LV_IMG_DECLARE(ui_img_cloud2rain3day_png);    // assets/cloud2Rain3Day.png
LV_IMG_DECLARE(ui_img_clearcloudday_png);    // assets/clearCloudDay.png
LV_IMG_DECLARE(ui_img_clearcloudnight_png);    // assets/clearCloudNight.png
LV_IMG_DECLARE(ui_img_cloud2day_png);    // assets/cloud2Day.png
LV_IMG_DECLARE(ui_img_cloud2night_png);    // assets/cloud2Night.png
LV_IMG_DECLARE(ui_img_cloud2rain3night_png);    // assets/cloud2Rain3Night.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
